# Generated by Django 3.1.2 on 2020-10-28 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='test',
            field=models.CharField(max_length=2),
        ),
    ]
